# Generated by Django 4.2.17 on 2025-10-21 12:01

from django.conf import settings
import django.contrib.postgres.fields
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from flowback.schedule.models import ScheduleTag


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0010_remove_scheduleevent_reminder_tasks_and_more'),
        ('group', '0054_workgroup_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='name'
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedulesubscription',
            name='subscribe_to_new_notification_tags',
            field=models.BooleanField(default=False, blank=True),
        ),
        migrations.AddField(
            model_name='schedulesubscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_subscription_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='origin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='origin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleTagSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=10)),
                ('schedule_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulesubscription')),
                ('schedule_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletag')),
            ],
        ),
        migrations.AddField(
            model_name='scheduletag',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='default_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_tag', to='schedule.scheduletag'),
        ),
        migrations.AddField(
            model_name='schedulesubscription',
            name='notification_tags',
            field=models.ManyToManyField(blank=True, through='schedule.ScheduleTagSubscription', to='schedule.scheduletag'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulesubscription',
            unique_together={('user', 'schedule')},
        )
    ]
