# Generated by Django 4.2.17 on 2025-10-21 16:23

from django.conf import settings
from django.db import migrations

# Populates the content_type fields for Schedule and ScheduleEvent
def migrate_schedule_origins(apps, schema_editor):
    Schedule = apps.get_model('schedule', 'Schedule')
    ScheduleEvent = apps.get_model('schedule', 'ScheduleEvent')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get ContentType instances for each model
    origins = {
        'user': ContentType.objects.get(app_label='user', model='user'),
        'group': ContentType.objects.get(app_label='group', model='group'),
        'group_poll': ContentType.objects.get(app_label='poll', model='poll'),
        'group_poll_proposal': ContentType.objects.get(app_label='poll', model='pollproposal'),
    }

    # Populate schedule content_type with origin fields
    for schedule in Schedule.objects.all():
        schedule.content_type = origins[schedule.origin_name]
        schedule.object_id = schedule.origin_id
        schedule.save()

    # Populate schedule event content_type with origin fields
    for event in ScheduleEvent.objects.all():
        event.content_type = origins[event.origin_name]
        event.object_id = event.origin_id
        event.save()


def populate_schedule_tags(apps, schema_editor):
    Schedule = apps.get_model('schedule', 'Schedule')
    ScheduleTag = apps.get_model('schedule', 'ScheduleTag')

    for schedule in Schedule.objects.all():
        schedule_tag = ScheduleTag.objects.create(name='default', schedule_id=schedule.id)
        schedule.default_tag = schedule_tag
        schedule.save()


def migrate_from_schedule_subscription_to_user_subscription(apps, schema_editor):
    ScheduleSubscription = apps.get_model('schedule', 'ScheduleSubscription')
    ScheduleEvent = apps.get_model('schedule', 'ScheduleEvent')
    Schedule = apps.get_model('schedule', 'Schedule')
    User = apps.get_model('user', 'User')
    Group = apps.get_model('group', 'Group')
    WorkGroup = apps.get_model('group', 'WorkGroup')

    print("HERE")

    # TODO keep previous schedule events intact
    ScheduleSubscription.objects.all().delete()

    # Create new user subscriptions
    for user in User.objects.all():
        schedule = user.schedule
        ScheduleSubscription.objects.create(user=user, schedule=schedule)

    # Create new group subscriptions
    for group in Group.objects.all():
        schedule = group.schedule
        group.schedule = schedule
        group.save()

        for group_user in group.groupuser_set.filter(active=True).all():
            ScheduleSubscription.objects.create(user=group_user.user, schedule=schedule)

        # Work groups as well
        for work_group in group.workgroup_set.all():
            for schedule_event in work_group.group.schedule.scheduleevent_set.filter(work_group__isnull=False).all():
                schedule_event.update(created_by=work_group)

            for workgroup_user in work_group.workgroupuser_set.filter(active=True).all():
                ScheduleSubscription.objects.create(user=workgroup_user.group_user.user, schedule=work_group.schedule)



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_scheduletag_schedule_content_type_schedule_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulesubscription',
            name='target'
        ),
        migrations.RunPython(migrate_schedule_origins),
        migrations.RunPython(populate_schedule_tags),
        migrations.RunPython(migrate_from_schedule_subscription_to_user_subscription),
        migrations.RemoveField(
            model_name='scheduleevent',
            name='reminders'
        ),
        migrations.RemoveField(
            model_name='scheduleevent',
            name='work_group'
        )
    ]
