# Generated by Django 4.2.17 on 2025-10-28 12:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedule', '0012_alter_schedulesubscription_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='origin_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='origin_name',
        ),
        migrations.RemoveField(
            model_name='scheduleevent',
            name='origin_id',
        ),
        migrations.RemoveField(
            model_name='scheduleevent',
            name='origin_name',
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletag'),
        ),
        migrations.AddField(
            model_name='scheduletagsubscription',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scheduletagsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ScheduleEventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='A list of user-defined tags', null=True, size=10)),
                ('locked', models.BooleanField(default=True, help_text='If set to true and user unsubscribes from the tag related to the event, the event will remain subscribed.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleevent')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulesubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
