# Generated by Django 4.2.17 on 2025-11-14 15:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0013_remove_schedule_origin_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleSubscription',
            new_name='ScheduleUser',
        ),
        migrations.RenameModel(
            old_name='ScheduleEventUserData',
            new_name='ScheduleEventSubscription',
        ),
    ]
