# Generated by Django 4.2.17 on 2025-11-14 15:26

import django.contrib.postgres.fields
from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_scheduleeventsubscription_scheduleuser_and_more'),
        ('group', '0054_workgroup_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleeventsubscription',
            old_name='subscription',
            new_name='schedule_user',
        ),
        migrations.RenameField(
            model_name='scheduletagsubscription',
            old_name='schedule_subscription',
            new_name='schedule_user',
        ),
        migrations.AddField(
            model_name='scheduleeventsubscription',
            name='reminders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=10),
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='reminders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=10),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='scheduletagsubscription',
            trigger=pgtrigger.compiler.Trigger(name='prevent_update_schedule_tag_subscription', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='01c1c794bc5de7e3431b961df4c2e360fcfbc88d', operation='UPDATE', pgid='pgtrigger_prevent_update_schedule_tag_subscription_b96cc', table='schedule_scheduletagsubscription', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='scheduletagsubscription',
            constraint=models.UniqueConstraint(fields=('schedule_user', 'schedule_tag'), name='unique_schedule_tag_subscription'),
        ),
    ]
