# Generated by Django 4.2.17 on 2025-11-18 14:35

from django.db import migrations, models


def populate_schedule_event_reminders(apps, schema_editor):
    ScheduleEvent = apps.get_model('schedule', 'ScheduleEvent')
    Schedule = apps.get_model('schedule', 'Schedule')
    ScheduleTag = apps.get_model('schedule', 'ScheduleTag')

    for schedule in Schedule.objects.all():
        if not schedule.default_tag:
            default_tag = ScheduleTag.objects.create(name='default', schedule_id=schedule.id)
            default_tag.save()

            schedule.default_tag = default_tag
            schedule.save()

        for event in schedule.scheduleevent_set.all():
            if not event.tag:
                event.tag = schedule.default_tag
                event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_alter_scheduleuser_schedule_alter_scheduleuser_user'),
    ]

    operations = [
        migrations.RunPython(populate_schedule_event_reminders)
    ]
