# Generated by Django 4.2.17 on 2025-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_add_schedule_default_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='tag',
            field=models.ForeignKey(on_delete=models.CASCADE, to='schedule.scheduletag')
        )
    ]
