# Generated by Django 4.2.17 on 2025-11-18 14:52

from django.db import migrations

def delete_poll_proposal_schedule_events(apps, schema_editor):
    ScheduleEvent = apps.get_model('schedule', 'ScheduleEvent')
    Schedule = apps.get_model('schedule', 'Schedule')

    ScheduleEvent.objects.filter(content_type__model='poll').delete()
    Schedule.objects.filter(content_type__model='poll').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_schedule_event_tag_required'),
    ]

    operations = [
        migrations.RunPython(delete_poll_proposal_schedule_events)
    ]
