# Generated by Django 4.2.17 on 2025-11-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedule', '0019_delete_poll_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
