# Generated by Django 4.2.17 on 2025-12-12 13:07

from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_alter_scheduleevent_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='title',
            field=models.TextField(validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='scheduletag',
            name='name',
            field=models.CharField(max_length=100, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
