# Generated by Django 4.2.7 on 2023-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_dark_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='configuration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
