# Generated by Django 4.2.16 on 2025-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_user_direct_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='post_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
