# Generated by Django 4.2.17 on 2025-11-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_onboarduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schedule',
        ),
    ]
