# Generated by Django 4.2.17 on 2025-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_user_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='action_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
