# Generated by Django 4.2.17 on 2025-12-12 13:07

import django.contrib.auth.validators
from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_report_action_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='action_description',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='report',
            name='post_type',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_config',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=120, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
