# Generated by Django 4.2.7 on 2023-12-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_remove_poll_voteenddategreaterthandelegatevoteenddate_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollproposal',
            name='blank_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollproposal',
            name='participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollproposal',
            name='positive_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
