# Generated by Django 4.2.7 on 2023-12-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_1_pollproposal_blank_votes_pollproposal_participants_and_more'),
        ('poll', '0020_remove_poll_polltypeisscheduleanddynamic_check_and_more'),
    ]

    operations = [
    ]
