# Generated by Django 4.2.7 on 2023-12-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_merge_20231218_1551'),
        ('poll', '0025_polldelegatevoting_mandate'),
    ]

    operations = [
    ]
