# Generated by Django 4.2.7 on 2024-01-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0026_merge_20231228_1414'),
        ('poll', '0026_pollproposal_attachments'),
    ]

    operations = [
    ]
