# Generated by Django 4.2.7 on 2024-01-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagechanneltopic_hidden'),
        ('poll', '0028_poll_message_channel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='message_channel_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.messagechanneltopic'),
        ),
    ]
