# Generated by Django 4.2.7 on 2024-02-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0027_polldelegatevoting_comment_section_and_more'),
        ('poll', '0029_alter_poll_message_channel_topic'),
    ]

    operations = [
    ]
