# Generated by Django 4.2.7 on 2024-02-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0028_alter_pollvotingtypecardinal_raw_score'),
        ('poll', '0030_merge_20240221_1545'),
    ]

    operations = [
    ]
