# Generated by Django 4.2.7 on 2024-03-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0029_alter_poll_description'),
        ('poll', '0031_merge_20240227_1644'),
    ]

    operations = [
    ]
