# Generated by Django 4.2.7 on 2024-04-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0024_alter_groupuser_chat_participant'),
        ('poll', '0033_pollvote_pollvote_unique_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollVote',
            new_name='PollPriority',
        ),
    ]
