# Generated by Django 4.2.7 on 2024-04-02 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0024_alter_groupuser_chat_participant'),
        ('poll', '0034_rename_pollvote_pollpriority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollProposalPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pollpriority',
            name='unique_vote',
        ),
        migrations.AddConstraint(
            model_name='pollpriority',
            constraint=models.UniqueConstraint(fields=('group_user', 'poll'), name='unique_poll_priority'),
        ),
        migrations.AddField(
            model_name='pollproposalpriority',
            name='group_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupuser'),
        ),
        migrations.AddField(
            model_name='pollproposalpriority',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposal'),
        ),
        migrations.AddConstraint(
            model_name='pollproposalpriority',
            constraint=models.UniqueConstraint(fields=('group_user', 'proposal'), name='unique_poll_proposal_priority'),
        ),
    ]
