# Generated by Django 4.2.7 on 2024-04-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0033_poll_allow_fast_forward'),
        ('poll', '0035_pollproposalpriority_remove_pollpriority_unique_vote_and_more'),
    ]

    operations = [
    ]
