# Generated by Django 4.2.7 on 2024-05-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0036_merge_20240424_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.IntegerField(choices=[(1, 'ranking'), (2, 'for_against'), (3, 'schedule'), (4, 'cardinal'), (1001, 'vote')]),
        ),
    ]
