# Generated by Django 4.2.16 on 2025-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0046_alter_poll_interval_mean_absolute_correctness'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollpredictionstatement',
            name='outcome',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
