# Generated by Django 4.2.17 on 2025-11-14 15:13

from django.db import migrations, models


def migrate_event_to_dates(apps, schema_editor):
    PollProposalTypeSchedule = apps.get_model('poll', 'PollProposalTypeSchedule')
    for schedule in PollProposalTypeSchedule.objects.select_related('event').all():
        if schedule.event:
            schedule.event_start_date = schedule.event.start_date
            schedule.event_end_date = schedule.event.end_date
            schedule.save(update_fields=['event_start_date', 'event_end_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0047_pollpredictionstatement_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polltypeschedule',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='polltypeschedule',
            name='schedule',
        ),
        migrations.RemoveConstraint(
            model_name='pollproposaltypeschedule',
            name='unique_proposaltypeschedule',
        ),
        migrations.AddField(
            model_name='pollproposaltypeschedule',
            name='event_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pollproposaltypeschedule',
            name='event_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(migrate_event_to_dates),
        migrations.AlterField(
            model_name='pollproposaltypeschedule',
            name='event_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pollproposaltypeschedule',
            name='event_start_date',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='pollproposaltypeschedule',
            name='event',
        ),
        migrations.AddConstraint(
            model_name='pollproposaltypeschedule',
            constraint=models.UniqueConstraint(fields=('proposal', 'event_start_date', 'event_end_date'), name='unique_proposaltypeschedule'),
        ),
        migrations.DeleteModel(
            name='PollTypeSchedule',
        ),
    ]
