# Generated by Django 4.2.17 on 2025-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0048_remove_polltypeschedule_poll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='schedule_poll_meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
