# Generated by Django 4.2.17 on 2025-12-12 13:07

from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0050_alter_poll_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollpredictionstatement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pollproposal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='pollphasetemplate',
            name='name',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='pollpredictionstatement',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='pollpredictionstatement',
            name='title',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='pollproposal',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='pollproposal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
