# Generated by Django 4.2.17 on 2026-01-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0051_pollpredictionstatement_active_pollproposal_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollproposaltypeschedule',
            name='preliminary_score',
            field=models.IntegerField(default=0),
        ),
    ]
