# Generated by Django 4.2.17 on 2025-10-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_alter_notification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationsubscriptiontag',
            unique_together={('subscription', 'name')},
        ),
    ]
