# Generated by Django 4.2.17 on 2025-10-28 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_alter_notificationsubscriptiontag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsubscriptiontag',
            name='reminders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, help_text='Reminder times for the given tag', null=True, size=None),
        ),
    ]
