# Generated by Django 4.2.17 on 2025-12-12 13:07

from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_alter_notificationsubscriptiontag_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationobject',
            name='message',
            field=models.TextField(max_length=2000, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='notificationobject',
            name='tag',
            field=models.CharField(help_text='Tag of the notification', max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='notificationsubscriptiontag',
            name='name',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
