# Generated by Django 4.2.16 on 2025-07-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0047_add_notification_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupthread',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
