# Generated by Django 4.2.17 on 2025-10-21 15:32

from django.db import migrations, models
import django.db.models.deletion


def create_schedule_for_each_workgroup(apps, schema_editor):
    WorkGroup = apps.get_model('group', 'WorkGroup')
    Schedule = apps.get_model('schedule', 'Schedule')
    for workgroup in WorkGroup.objects.all():
        schedule = Schedule.objects.create(created_by=workgroup)
        workgroup.schedule = schedule
        workgroup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0053_fix_grouppermissions_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.schedule'),
        ),
        migrations.RunPython(create_schedule_for_each_workgroup),
    ]
