# Generated by Django 4.2.17 on 2025-11-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0054_workgroup_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='schedule',
        ),
    ]
