# Generated by Django 4.2.17 on 2025-11-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0055_remove_group_schedule_remove_workgroup_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='default_permission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.grouppermissions'),
        ),
    ]
