# Generated by Django 4.2.17 on 2025-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0056_alter_group_default_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='schedule_event_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='schedule_event_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='schedule_event_update',
            field=models.BooleanField(default=False),
        ),
    ]
