# Generated by Django 4.2.17 on 2025-11-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0057_grouppermissions_schedule_event_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppermissions',
            options={'verbose_name': 'Group permission', 'verbose_name_plural': 'Group permissions'},
        ),
        migrations.AlterModelOptions(
            name='grouptags',
            options={'verbose_name': 'Group tag', 'verbose_name_plural': 'Group tags'},
        ),
    ]
