# Generated by Django 4.2.17 on 2025-12-12 13:07

from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0058_alter_grouppermissions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(unique=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='groupfolder',
            name='name',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='grouppermissions',
            name='role_name',
            field=models.TextField(default='default', validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='grouptags',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='grouptags',
            name='name',
            field=models.TextField(validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='groupthread',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='groupthread',
            name='title',
            field=models.CharField(max_length=200, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
