# Generated by Django 4.2.17 on 2025-12-12 13:07

from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_alter_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True, max_length=10000, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
