# Generated by Django 4.2.17 on 2025-12-12 13:07

from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=2000, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(default='message', max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='messagechannel',
            name='origin_name',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='messagechannel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
        migrations.AlterField(
            model_name='messagechanneltopic',
            name='name',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
