# Generated by Django 4.2.17 on 2025-12-12 13:07

from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filesegment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesegment',
            name='file_name',
            field=models.CharField(max_length=255, validators=[flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
